config/routes.rb
Motiv8tion::Application.routes.draw do
  
  
  
  
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :goals do
    member do
      get  'share' => "goals#ask_share", :as => 'share'
      post 'share' => "goals#share", :as => 'share'
      get  'phone' => "goals#ask_phone", :as => 'phone'
      post 'phone' => "goals#phone", :as => 'phone'
    end
  end

  
  root :to => "main#index"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, :order => "deadline asc"
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # 
  devise :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :database_authenticatable, :registerable


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :goals



  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      user = User.new(:email => data["email"], :password => Devise.friendly_token[0,20])  
      # user.access_code =  
      user.first_name = data["first_name"]
      user.last_name = data["last_name"]
      user.fb_id = data["id"]
      user.save
      user
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]    
        user.email = data["email"]
        user.first_name = data["first_name"]
        user.last_name = data["last_name"]
      end
    end
  end

  def facebook_post(message)

  end


  def name
    first_name + " " + last_name
  end

  def image_url
    "https://graph.facebook.com/#{self.fb_id}/picture"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def authenticate_user!
  if !current_user
    # This should work, but session is lost. See https://github.com/plataformatec/devise/issues/1357
    # session[:return_to] = request.fullpath
    redirect_to user_omniauth_authorize_path(:google_apps, :origin => request.fullpath)
  end
end   

  def after_sign_in_path_for(resource)
    # This should work, but session is lost. See https://github.com/plataformatec/devise/issues/1357
      #               # return_to = session[:return_to]
      #                 # session[:return_to] = nil
    return_to = request.env['omniauth.origin']
    stored_location_for(resource) || return_to || root_path  
  end   
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = current_user.goals
  end

  def show
    @goal = current_user.goals.find_by_id(params[:id])
  end

  def new
    @goal = Goal.new(params[:goal]||{})
  end

  def create
    @goal = current_user.goals.build(params[:goal])
    if current_user.save
      redirect_to share_goal_path(@goal)
    else
      render :new
    end
  end

  def edit
    @goal = current_user.goals.find_by_id(params[:id])
  end

  def update
    @goal = current_user.goals.find_by_id(params[:id])
    @goal.attributes = params[:goal]
    if @goal.save
      redirect_to :goals
    else
      render :edit
    end
  end

  def destroy
    @goal = current_user.goals.find_by_id(params[:id])
    @goal.destroy
  end
  
  def ask_share
    @goal = current_user.goals.find_by_id(params[:id])
    @message = "I want to #{@goal.name} by #{@goal.deadline.strftime("%B %e, %Y")}. Give me your support at #{root_url}"
  end
  def share
    @goal = current_user.goals.find_by_id(params[:id])
    if s = session[:omniauth] && c = s["credentials"] && toekn = c["token"]
      @graph = Koala::Facebook::API.new(token)
      @graph.put_object("me", "feed", :message => params[:message]) 
    end
    redirect_to phone_goal_path(@goal)
  end

  def ask_phone
    @goal = current_user.goals.find_by_id(params[:id])
    @message = "Remember, you said you wanted to #{@goal.name}. How's that going?"
  end
  def phone
    @goal = current_user.goals.find_by_id(params[:id])
    require 'contact'
    current_user.update_attribute(:phone_number, params[:phone_number])
    Contact.sms(current_user.phone_number, params[:message])
    redirect_to goal_path(@goal)
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if current_user
      redirect_to :goals
    end
  end

end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in @user
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      #redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/goals/_form.html.haml
= simple_nested_form_for(@goal) do |f|
  .step.active
    = f.input :name
    = f.input :reason, :input_html => { :rows => 3 }
    = f.input :deadline, :as => :date
    %a.next(href="#") Next
  .step
    
    .tasks
      %h4 My very next step is...
      %input.task(name="goals[tasks][0]" type="text")
    %a.back(href="#") Back
    %a.next(href="#") Next


  - unless current_user
    .step
      %h4.connect Connect with Facebook to give and receive support to accomplish your goals
      %a.back(href="#") Back
      %a(href="#{user_omniauth_authorize_path(:facebook)}" class="popup facebook-connect-button" data-width="600" data-height="400")

app/views/goals/ask_phone.html.haml
%h4.ask Do you want text message reminders to continue working on your goal?

= simple_form_for(@goal, :url => phone_goal_path(@goal), :method =>"POST") do |f|
  %p.phone
    %label Phone
    %input(name="phone_number" type="text")
  %p  
    %label.textlabel Text Message to Send
    %textarea(name="message" rows="3" cols="70")= @message
  = f.button :submit, "Save"
= link_to "Skip?", goal_path(@goal) 

app/views/goals/ask_share.html.haml
%span.connect
  Connect with Facebook to give and receive support to accomplish your goals.

= simple_form_for(@goal, :url => share_goal_path, :method =>"POST") do |f|
  %textarea(name="message" rows="3" cols="70")= @message
  = f.button :submit, "Share"

app/views/goals/edit.html.haml
%h1 Change Your Goal
= render 'form'

:coffeescript
  $ () ->
    $(".step").addClass("active")

app/views/goals/index.html.erb
<img src="/assets/profile.png" />

app/views/goals/new.html.haml
%h1 Make a New Goal 
= render 'form'
:coffeescript
  window.nextStep = () ->
    lastStep = $(".step.active")
    next = lastStep.next(".step")
    if next.length
      next.fadeIn().addClass("active")
      lastStep.hide().removeClass("active")
    else
      $("form").submit()
  window.prevStep = () ->
    step = $(".step.active")
    step.prev(".step").fadeIn().addClass("active")
    step.hide().removeClass("active")

  $ () ->
    $(".next").click () ->
      nextStep()  
    $(".back").click () ->
      prevStep()

app/views/goals/show.html.erb
<img src="/assets/progress.png" />
<a href="/goals"/>My Goals</a>

app/views/goals/show.html.haml
= link_to "My Profile", goals_path

%h1 My Progress Page
.status
  %p 
    I want to 
    %strong= @goal.name
  - unless @goal.reason.blank?
    %p
      Because 
      %strong= @goal.reason
  - if @goal.tasks.first
    %p
      My next action is to
      %strong= @goal.tasks.first.name
  %p
    %button Stuck? Ask for help!



%h2 History
.history
  I have already:
  %ul
    - @goal.tasks.each do |task|
      %li= task.name

  I have accomplished 
  %strong 100%
  of my goals on time!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motiv8ion</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Satisfy|Terminal+Dosis' rel='stylesheet' type='text/css'>
<!-- start Mixpanel --><script type="text/javascript">var mpq=[];mpq.push(["init","8753e85e9927989cefca7ab069f0672e"]);(function(){var b,a,e,d,c;b=document.createElement("script");b.type="text/javascript";b.async=true;b.src=(document.location.protocol==="https:"?"https:":"http:")+"//api.mixpanel.com/site_media/js/api/mixpanel.js";a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a);e=function(f){return function(){mpq.push([f].concat(Array.prototype.slice.call(arguments,0)))}};d=["init","track","track_links","track_forms","register","register_once","identify","name_tag","set_config"];for(c=0;c<d.length;c++){mpq[d[c]]=e(d[c])}})();
</script><!-- end Mixpanel -->
</head>
<body>
	<div id="header">
  
		<div class="inner">
      <a id="logo"></a><div class="pitch">Helping you achieve your goals with the help of your friends.</div>
      
      <div class="clear"></div>
		</div>
    
	</div>
  
      <%= yield :header %>
  <p class="notice"><%= flash[:notice] %></p>
  <p class="error"><%= flash[:error] %></p> 

  <% if Rails.env.development? && !current_user %>
    <%= link_to "Testing Login", new_user_session_path %>
  <% end %>
	<div id="container">				
    <div id="body">
      <div class="inner">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <div class="inner">
      </div>
    </div>
</div>
      <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, :method => "delete" %>
      <% end %>
      

</body>
</html>

app/views/main/index.html.erb
<% content_for :header do %> 
    <div id="banner">
			<div class="inner">
				<form action="/goals/new/" id="splash" method="GET">
					<span id="iwanto">I want to: </span><input name="goal[name]" id="goal" placeholder="e.g. learn chinese, lose weight, learn the guitar" type="text"/> 
					<input type="submit" id="submit" value="Get Motivated!" />
				</form>    
			</div>
		</div>
<% end %>
		<div class="inner">	
		<img src="/assets/newgoals.png" />
		</div>
<script>
  $("#goal").autocomplete({
        source: ["start a business", "start working out", "stop smoking", "start running", "start writing"]
   });
</script>